### ISSUE TITLE
Module not found: Can't resolve 'quill.imageUploader.js'

### ISSUE THREAD

**Issue by tsvetann** [enlear/quill-image-uploader-nextjs#1]
Module not found: Can't resolve 'quill.imageUploader.js' Your package isn't working for me

**Comment by cagriakar** [comment]
@tsvetann 
try to import like

`import ImageUploader from "@writergate/quill-image-uploader-nextjs"`

this should work as per config in package.json shown below

<img width="373" alt="image" src="https://user-images.githubusercontent.com/55461100/195044250-17c836f6-6671-47e7-90c2-d20c2b7b7b1c.png">
